### ISSUE TITLE
Non-webpack/browerify loading (AMD/requirejs/native)

### ISSUE THREAD

**Issue by ensemblebd** [mohsen1/json-formatter-js#64]
Sadly I had to modify it to get it work on particular environments. 
Would I be out of scope to request that you provide a wrapper (aka polyfill) for module.exports?

That way it can be used via requirejs, or via <script> tags?

Love this though, thank you!

**Comment by mohsen1** [comment]
I used to package for UMD which lets you use it via a global variable but since most people are now using Webpack or similar tools I figured it's not necessary anymore. broserifying it won't be too difficult on your end so I'll let you do that and keep this module the way it is. :)

**Comment by ensemblebd** [comment]
Alright. Was worth a try anyway

**Comment by jenguidanos** [comment]
I have updated my dependencies and my app has stopped working for this reason (module.exports on json-formatter). It's a bit sad because I was very happy but I'm going to stop using it, I don't have time to "fix" this on my own (I use gulp+uglify). I think it might have been interesting to include a universal UMD loader to increase compatibility with other systems that don't use Webpack/Browserify.

My Firefox Web Console:
![js-formatter](https://user-images.githubusercontent.com/25366048/47007704-1b876800-d139-11e8-9d8f-d131c03df3b0.jpg)

Anyway, thank you for your work :)

**Comment by mohsen1** [comment]
@jenguidanos you can lock to an older version. newer versions are not that different
